name: checks
on:
  pull_request:
    branches:
      - main

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    container:
      image: nesnds/ndp-deployment-container:3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Copy commit-lint config
        run: cp -r /commit-lint .
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ./commit-lint/commitlint.config.js

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Disabling because we prefer more control over the version of the TypeScript linter
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_ES: false

  typescript-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install Dependencies
        run: npm ci
        env:
          GITHUB_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint TypeScript Files
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Run unit tests
        run: npm run test
